name: CI

on: [push, pull_request]

jobs:
  build:
    env:
      PYTHONPATH: yugiohbot
      ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
      PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r yugiohbot/requirements.txt
          pip install pytest-cov codecov

      - name: Run Tests
        run: pytest --cov=./

      - name: Report coverage
        run: codecov